Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: 'accatpics13329358923483337'
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0e9107ed11be76fde'    